apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smi-trafficsplit-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/tylermac92/k3s-gitops-lab.git
    targetRevision: HEAD
    path: apps/smi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

