apiVersion: v1
kind: Service
metadata:
  name: podinfo-stable
  namespace: demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podinfo-blue
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: podinfo
  namespace: demo
spec:
  service: podinfo-stable
  backends:
    - service: podinfo-blue
      weight: 50
    - service: podinfo-green
      weight: 50

