apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: 1.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated: { prune: true, selfHeal: true }

